# Generated by Django 4.1 on 2022-11-17 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='student_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('file', models.FileField(upload_to='pdf_files')),
            ],
        ),
        migrations.CreateModel(
            name='student_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_info', models.CharField(blank=True, max_length=3000000)),
                ('student_token', models.CharField(default='5703d2cf-7eeb-48e0-acf7-7ab150aadacb', max_length=3000000, unique=True)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
